Repository AY2324S2-CS2103-F09-4/tp, pull requests merged in 2024-04, with the labels that each got.

#64 Update diagrams and MSS for user developer guides, Fix `add-note` UI
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.documentation, priority.low

#69 Fix merge issues
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.bug, priority.high

#72 Update user and developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
Labels: type.documentation, priority.low

#68 Update Find for Illness
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/illness/Illness.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/illness/IllnessTest.java
Labels: priority.low

#71 Add undo support for appointment commands
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/commands/EditNoteCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditNoteCommandTest.java
Labels: priority.medium

#73 Minor bug fix for list command predicate reload
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: type.bug

#77 Update to BirthDate, documentation
  build.gradle
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/BirthDate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/model/person/BirthDateTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.documentation, priority.low

#78 Update ui image
  docs/images/Ui.png
Labels: type.documentation

#141 Fix `edit-an` error and `NoteCard` UI
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/resources/view/NoteListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.bug, type.others, priority.low

#143 Fix docs and `edit` issues
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
Labels: type.documentation, type.bug, priority.low

#147 Update UG, DG and some minor code functionality to address PE-D issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Nric.java
Labels: type.bug, priority.medium

#149 Update developer guide for footer issue
  docs/DeveloperGuide.md
Labels: type.bug, priority.low

#146 Update site header content to "HealthSync"
  docs/_sass/minima/_base.scss
Labels: type.documentation, priority.low

#150 Update documentation and `Find` for gender
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.bug, priority.low

#144 Update correct naming of data file
  docs/UserGuide.md
Labels: type.documentation, priority.low

#151 Refactor PersonCard
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.low

#152 Update broken links
  docs/DeveloperGuide.md
Labels: type.documentation, priority.low
