Repository AY2324S2-CS2103-F09-4/tp, pull requests merged in 2024-03, with the labels that each got.

#25 Documentation for list/add/edit patient medical records
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/jmsandiegoo.png
Labels: type.documentation, priority.low

#23 Documentation for edit/listing appointment note
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/sebinaum.png
  docs/team/sebin.md
Labels: type.documentation, priority.low

#26 Documentation for help command
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/rickkoh.png
  docs/team/rickkoh.md
Labels: type.documentation, priority.low

#24 Groundwork for appointment notes
  build.gradle
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/note/Description.java
  src/main/java/seedu/address/model/person/note/Note.java
  src/main/java/seedu/address/model/person/note/exceptions/NoteNotFoundException.java
  src/main/java/seedu/address/model/person/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdapatedNote.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/note/DescriptionTest.java
  src/test/java/seedu/address/model/person/note/NoteTest.java
  src/test/java/seedu/address/model/person/tag/TagTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/storage/JsonAdapatedNoteTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.others, priority.medium

#27 Documentation for delete command
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/raysonchia.png
  docs/team/raysonchia.md
Labels: type.documentation, priority.low

#30 Support for `add-an` command
  build.gradle
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/note/NoteTest.java
Labels: type.others, priority.medium

#36 Support for `add` patient medical record command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/BirthDate.java
  src/main/java/seedu/address/model/person/DrugAllergy.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/illness/Illness.java
  src/main/java/seedu/address/model/person/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedIllness.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/person/illness/IllnessTest.java
  src/test/java/seedu/address/model/person/tag/TagTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.high

#35 Add Find command documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.documentation, priority.low

#40 Update team roles in AboutUs.md file
  docs/AboutUs.md
Labels: type.documentation, priority.low

#32 Support for `list-an` command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/ListNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListNoteCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/note/Note.java
  src/main/java/seedu/address/model/person/note/exceptions/DuplicateNoteException.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NoteCard.java
  src/main/java/seedu/address/ui/NoteListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NoteListCard.fxml
  src/main/resources/view/NoteListPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListNoteCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/note/NoteTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.others, priority.medium

#41 Update storage class diagram to include `JsonAdapatedNote`
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.documentation, priority.low

#44 Update model class diagram to include `Note` and `Description`
  docs/diagrams/ModelClassDiagram.puml
Labels: type.documentation, priority.high

#43 Update model class uml diagram to include patient medical record attributes
  docs/diagrams/ModelClassDiagram.puml
Labels: type.documentation, priority.low

#42 Support for `edit` patient medical record command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/DrugAllergy.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.high

#47 Update window title to "HealthSync"
  src/main/resources/view/MainWindow.fxml
Labels: type.others, priority.low

#48 Update UI Class Diagram to include `NoteListPanel` and `NoteCard`
  docs/diagrams/UiClassDiagram.puml
Labels: type.documentation, priority.low

#45 Support for `find` patient medical record command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/predicates/BirthdateContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/DrugAllergyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/GenderContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/IllnessContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/NricContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/PhoneContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: priority.medium

#55 Support for `edit-an` command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditNoteDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/EditNoteDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.others, priority.medium

#58 Enable assertions
  build.gradle
Labels: type.others, priority.low

#52 Add NoteCard and connect NoteListPanel to PersonListPanel
  docs/diagrams/UiClassDiagram.puml
Labels: type.documentation, priority.low

#61 Update user and developer guide docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/diagrams/UndoState0.puml
  docs/diagrams/UndoState1.puml
  docs/diagrams/UndoState2.puml
  docs/diagrams/UndoState3.puml
  docs/diagrams/UndoState4.puml
  docs/images/CommitActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram-Logic.png
  docs/images/UndoState0.png
  docs/images/UndoState1.png
  docs/images/UndoState2.png
  docs/images/UndoState3.png
  docs/images/UndoState4.png
Labels: type.documentation, priority.medium

#63 Update developer guide
  docs/DeveloperGuide.md
  src/main/java/seedu/address/MainApp.java
Labels: type.documentation, priority.low

#62 Update UML diagrams and add DG/UG draft
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.documentation, priority.low

#59 Update to `Find` command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/predicates/ContainsKeywordsPredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/predicates/BirthdateContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/DrugAllergyContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/GenderContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/IllnessContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/NricContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.low
